//
//  PreferredRouteForLine.swift
//  naczas
//
//  Created by Stanisław Makijenko on 02/03/2025.
//

import Foundation

let preferredMainRoute: [String : [PreferredRouteModel]] = [
    "1" : [PreferredRouteModel(routeName: "TD-5NAR", direction: "pl.Narutowicza"), PreferredRouteModel(routeName: "TX-A04ZN", direction: "Annopol")],
    "2" : [PreferredRouteModel(routeName: "TX-11WIN", direction: "Winnica"), PreferredRouteModel(routeName: "TX-MML11", direction: "Metro Młociny")],
    "3" : [PreferredRouteModel(routeName: "TP-GCW", direction: "Gocławek"), PreferredRouteModel(routeName: "TP-ANN", direction: "Annopol")],
    "4" : [PreferredRouteModel(routeName: "TP-WYS", direction: "Wyścigi"), PreferredRouteModel(routeName: "TP-ZEW", direction: "Żerań Wschodni")],
    "6" : [PreferredRouteModel(routeName: "TP-MML", direction: "Metro Młociny"), PreferredRouteModel(routeName: "TP-GCW", direction: "Gocławek")],
    "7" : [PreferredRouteModel(routeName: "Custom7KawęczyńskaBazylika", direction: "Kawęczyńska Bazylika"), PreferredRouteModel(routeName: "Custom7PlNarutowicza", direction: "pl.Narutowicza")],
    "9" : [PreferredRouteModel(routeName: "TP-GCW", direction: "Gocławek"), PreferredRouteModel(routeName: "TP-OKE", direction: "P+R Al.Krakowska")],
    "10" : [PreferredRouteModel(routeName: "TP-GOR", direction: "Os.Górczewska"), PreferredRouteModel(routeName: "TP-WYS", direction: "Wyścigi")],
    "11" : [PreferredRouteModel(routeName: "TX-SLC76", direction: "Sielce"), PreferredRouteModel(routeName: "TX-CMW06", direction: "Cm.Wolski")],
    "13" : [PreferredRouteModel(routeName: "TP-CMW", direction: "Cm.Wolski"), PreferredRouteModel(routeName: "TP-KAW", direction: "Kawęczyńska-Bazylika")],
    "14" : [PreferredRouteModel(routeName: "Custom14PlNarutowicza", direction: "pl.Narutowicza"), PreferredRouteModel(routeName: "Custom14MiasteczkoWilanow", direction: "Miasteczko Wilanów")],
    "15" : [PreferredRouteModel(routeName: "TP-MPT", direction: "Marymont-Potok"), PreferredRouteModel(routeName: "TP-OKE", direction: "P+R Al.Krakowska")],
    "16" : [PreferredRouteModel(routeName: "TP-MWL", direction: "Miasteczko Wilanów"), PreferredRouteModel(routeName: "Custom16Piaski", direction: "Piaski")],
    "17" : [PreferredRouteModel(routeName: "TP-WIN", direction: "Winnica"), PreferredRouteModel(routeName: "TP-SLU", direction: "PKP Służewiec")],
    "18" : [PreferredRouteModel(routeName: "TP-SLU", direction: "PKP Służewiec"), PreferredRouteModel(routeName: "TP-FSO", direction: "Żerań FSO")],
    "20" : [PreferredRouteModel(routeName: "TP-BOE", direction: "Boernerowo"), PreferredRouteModel(routeName: "TP-FSO", direction: "Żerań FSO")],
    "22" : [PreferredRouteModel(routeName: "TP-PIA", direction: "Piaski"), PreferredRouteModel(routeName: "TP-WIA", direction: "Wiatraczna")],
    "23" : [PreferredRouteModel(routeName: "TP-STA", direction: "Czynszowa"), PreferredRouteModel(routeName: "TP-NBM", direction: "Nowe Bemowo")],
    "24" : [PreferredRouteModel(routeName: "TP-NBM", direction: "Nowe Bemowo"), PreferredRouteModel(routeName: "TP-GCW", direction: "Gocławek")],
    "25" : [PreferredRouteModel(routeName: "Custom25PlNarutowicza", direction: "pl.Narutowicza"), PreferredRouteModel(routeName: "Custom25Annopol", direction: "Annopol")],
    "26" : [PreferredRouteModel(routeName: "TP-WIA", direction: "Wiatraczna"), PreferredRouteModel(routeName: "TP-MML", direction: "Metro Młociny")],
    "27" : [PreferredRouteModel(routeName: "TP-MRM", direction: "Metro Marymont"), PreferredRouteModel(routeName: "TP-CMW", direction: "Cm.Wolski")],
    "28" : [PreferredRouteModel(routeName: "TP-DWK", direction: "Dw.Wschodni (Kijowska)"), PreferredRouteModel(routeName: "TP-GOR", direction: "os.Górczewska")],
    "31" : [PreferredRouteModel(routeName: "TP-WIE71", direction: "Metro Wierzbno"), PreferredRouteModel(routeName: "TP-71SZW", direction: "PKP Służewiec")],
    "33" : [PreferredRouteModel(routeName: "TP-KIE", direction: "Kielecka"), PreferredRouteModel(routeName: "TP-MML", direction: "Metro Młociny")],
    "102" : [PreferredRouteModel(routeName: "TX-OLSV", direction: "PKP Olszynka Grochowska"), PreferredRouteModel(routeName: "TP-MSN", direction: "Metro Stadion Narodowy")],
    "103" : [PreferredRouteModel(routeName: "Custom103MetroMłociny", direction: "Metro Młociny"), PreferredRouteModel(routeName: "Custom103DwZachodni", direction: "Dw.Zachodni")],
    "104" : [PreferredRouteModel(routeName: "TP-BRZ", direction: "Brzeziny"), PreferredRouteModel(routeName: "TP-MBR", direction: "Metro Bródno")],
    "105" : [PreferredRouteModel(routeName: "Custom105RondoDaszyńskiego", direction: "Rondo Daszyńskiego"), PreferredRouteModel(routeName: "Custom105OsGórczewska", direction: "os.Górczewska")],
    "106" : [PreferredRouteModel(routeName: "TP-OST", direction: "Ostroroga"), PreferredRouteModel(routeName: "TP-MAT", direction: "Mariensztat")],
    "107" : [PreferredRouteModel(routeName: "Custom107Esperanto", direction: "Esperanto"), PreferredRouteModel(routeName: "Custom107MetroWilanowska", direction: "Metro Wilanowska")],
    "108" : [PreferredRouteModel(routeName: "TO-LOS", direction: "Łososiowa"), PreferredRouteModel(routeName: "TP-PTK", direction: "pl.Trzech Krzyży")],
    "110" : [PreferredRouteModel(routeName: "TX-MRM-M", direction: "Metro Marymont"), PreferredRouteModel(routeName: "TO-CHL", direction: "CH Łomianki")],
    "111" : [PreferredRouteModel(routeName: "TP-ESP", direction: "Esperanto"), PreferredRouteModel(routeName: "TP-GOC", direction: "Gocław")],
    "112" : [PreferredRouteModel(routeName: "TP-NBM", direction: "Nowe Bemowo"), PreferredRouteModel(routeName: "TP-CHM-K", direction: "CH Marki")],
    "114" : [PreferredRouteModel(routeName: "TP-BRP", direction: "Bródno-Podgrodzie"), PreferredRouteModel(routeName: "TP-UXW", direction: "Młociny-UKSW")],
    "115" : [PreferredRouteModel(routeName: "TP-MOL-Y", direction: "PKP Mokry Ług"), PreferredRouteModel(routeName: "TP-ALE-Y", direction: "Aleksandrów")],
    "116" : [PreferredRouteModel(routeName: "TP-CHO", direction: "Chomiczówka"), PreferredRouteModel(routeName: "TX-WLW4", direction: "Wilanów")],
    "117" : [PreferredRouteModel(routeName: "TP-DWC", direction: "Dw.Centralny"), PreferredRouteModel(routeName: "TP-GOC", direction: "Gocław")],
    "118" : [PreferredRouteModel(routeName: "Custom118Mariensztat", direction: "Mariensztat"), PreferredRouteModel(routeName: "Custom118Spartańska", direction: "Spartańska")],
    "119" : [PreferredRouteModel(routeName: "TX-RAKV", direction: "Rakowiecka-Sanktuarium"), PreferredRouteModel(routeName: "TX-WIGV", direction: "Wiśniowa Góra")],
    "120" : [PreferredRouteModel(routeName: "Custom120Olesin", direction: "Olesin"), PreferredRouteModel(routeName: "Custom120DwWschodni", direction: "Dw.Wschodni (Kijowska)")],
    "121" : [PreferredRouteModel(routeName: "TX-MRMHV", direction: "Metro Marymont"), PreferredRouteModel(routeName: "TP-CHO-M", direction: "Chomiczówka")],
    "122" : [PreferredRouteModel(routeName: "TX-GOR03", direction: "os.Górczewska"), PreferredRouteModel(routeName: "TX-GWI02", direction: "Gwiaździsta")],
    "123" : [PreferredRouteModel(routeName: "TP-DWL", direction: "Dw.Wschodni (Lubelska)"), PreferredRouteModel(routeName: "TP-DWK", direction: "Dw.Wschodni (Kijowska)")],
    "124" : [PreferredRouteModel(routeName: "TX-OKE17", direction: "P+R Al.Krakowska"), PreferredRouteModel(routeName: "TP-PAL", direction: "Paluch")],
    "125" : [PreferredRouteModel(routeName: "TP-MIE", direction: "Międzylesie"), PreferredRouteModel(routeName: "TP-MSN", direction: "Metro Stadion Narodowy")],
    "126" : [PreferredRouteModel(routeName: "TP-CHT-K", direction: "CH Targówek"), PreferredRouteModel(routeName: "TP-TAR-K", direction: "Tarchomin")],
    "127" : [PreferredRouteModel(routeName: "Custom127UrsusRatusz", direction: "Ursus Ratusz"), PreferredRouteModel(routeName: "Custom127Browarna", direction: "Browarna")],
    "128" : [PreferredRouteModel(routeName: "TP-SZC", direction: "Szczęśliwice"), PreferredRouteModel(routeName: "TP-PIL", direction: "Pl.Piłsudskiego")],
    "129" : [PreferredRouteModel(routeName: "TP-KOL", direction: "Koło"), PreferredRouteModel(routeName: "TP-PKU", direction: "PKP Ursus")],
    "130" : [PreferredRouteModel(routeName: "Custom130ECSiekierki", direction: "EC Siekierki"), PreferredRouteModel(routeName: "Custom130MetroWilanowska", direction: "Metro Wilanowska")],
    "131" : [PreferredRouteModel(routeName: "Custom131DwCentralny", direction: "Dw.Centralny"), PreferredRouteModel(routeName: "Custom131Sadyba", direction: "Sadyba")],
    "132" : [PreferredRouteModel(routeName: "TP-DER", direction: "Os.Derby"), PreferredRouteModel(routeName: "TP-MRM", direction: "Metro Marymont")],
    "133" : [PreferredRouteModel(routeName: "TP-TRC", direction: "Tarchomin"), PreferredRouteModel(routeName: "TP-CHS", direction: "Choszczówka")],
    "134" : [PreferredRouteModel(routeName: "TP-MRM-S", direction: "Metro Marymont"), PreferredRouteModel(routeName: "TX-OLE-S", direction: "Olesin")],
    "135" : [PreferredRouteModel(routeName: "TO-OLS", direction: "PKP Olszynka Grochowska"), PreferredRouteModel(routeName: "TP-HAL", direction: "pl.Hallera")],
    "136" : [PreferredRouteModel(routeName: "TP-NAT", direction: "Natolin Płn."), PreferredRouteModel(routeName: "TP-OST", direction: "Ostroroga")],
    "138" : [PreferredRouteModel(routeName: "TP-BOK", direction: "Natolin Płn."), PreferredRouteModel(routeName: "TP-UTS", direction: "Utrata")],
    "139" : [PreferredRouteModel(routeName: "Custom139OgródBotaniczny", direction: "Ogród Botaniczny"), PreferredRouteModel(routeName: "Custom139OsKabaty", direction: "Os.Kabaty")],
    "140" : [PreferredRouteModel(routeName: "TP-MTR", direction: "Metro Trocka"), PreferredRouteModel(routeName: "TP-CZS", direction: "Czarna Struga")],
    "141" : [PreferredRouteModel(routeName: "TP-OKE", direction: "P+R Al.Krakowska"), PreferredRouteModel(routeName: "TP-OST", direction: "Witolin")],
    "142" : [PreferredRouteModel(routeName: "TP-ALE", direction: "Aleksandrów"), PreferredRouteModel(routeName: "TP-WIA", direction: "Wiatraczna")],
    "143" : [PreferredRouteModel(routeName: "TP-PML", direction: "Pomnik Lotnika"), PreferredRouteModel(routeName: "TP-RKL", direction: "Rembertów-Kolonia")],
    "145" : [PreferredRouteModel(routeName: "TP-WIA", direction: "Wiatraczna"), PreferredRouteModel(routeName: "TP-FSO", direction: "Żerań FSO")],
    "146" : [PreferredRouteModel(routeName: "TP-DWL", direction: "Dw.Wschodni (Lubelska)"), PreferredRouteModel(routeName: "TP-FAL", direction: "Falenica")],
    "147" : [PreferredRouteModel(routeName: "TP-MIL", direction: "Stara Miłosna (Ułańska)"), PreferredRouteModel(routeName: "TP-DWL", direction: "Dw.Wschodni (Lubelska)")],
    "148" : [PreferredRouteModel(routeName: "TX-WIA", direction: "Wiatraczna"), PreferredRouteModel(routeName: "TX-LOT", direction: "Terminal Autokarowy")],
    "149" : [PreferredRouteModel(routeName: "TX-GRO", direction: "Groty"), PreferredRouteModel(routeName: "TP-MBE", direction: "Metro Bemowo")],
    "150" : [PreferredRouteModel(routeName: "TP-DZI", direction: "Dziekanów Leśny"), PreferredRouteModel(routeName: "TX-MML03", direction: "Metro Młociny")],
    "151" : [PreferredRouteModel(routeName: "TP-REH", direction: "Rechniewskiego"), PreferredRouteModel(routeName: "TP-MPL", direction: "pl.Konstytucji")],
    "152" : [PreferredRouteModel(routeName: "TP-DER", direction: "os.Derby"), PreferredRouteModel(routeName: "TP-TRC", direction: "Tarchomin")],
    "153" : [PreferredRouteModel(routeName: "TP-PAS", direction: "Pastuszków"), PreferredRouteModel(routeName: "TP-RKL", direction: "Rembertów-Kolonia")],
    "154" : [PreferredRouteModel(routeName: "Custom154DwZachodni", direction: "Dw.Zachodni"), PreferredRouteModel(routeName: "Custom154PRAlKrakowska", direction: "P+R Al.Krakowska")],
    "156" : [PreferredRouteModel(routeName: "TX-DWK", direction: "Dw.Wschodni (Kijowska)"), PreferredRouteModel(routeName: "TP-MML", direction: "Metro Młociny")],
    "157" : [PreferredRouteModel(routeName: "Custom157Gwiaździsta", direction: "Gwiaździsta"), PreferredRouteModel(routeName: "Custom157Szczęśliwice", direction: "Szczęśliwice")],
    "158" : [PreferredRouteModel(routeName: "TP-CHR", direction: "CH Reduta"), PreferredRouteModel(routeName: "TP-OST", direction: "Witolin")],
    "159" : [PreferredRouteModel(routeName: "TP-MSI", direction: "Małe Siekierki"), PreferredRouteModel(routeName: "TP-BLC", direction: "CH Blue City")],
    "160" : [PreferredRouteModel(routeName: "TP-DWCT", direction: "Dw.Centralny"), PreferredRouteModel(routeName: "TP-GROT", direction: "Grodzisk")],
    "161" : [PreferredRouteModel(routeName: "Custom161Olecka", direction: "Olecka"), PreferredRouteModel(routeName: "Custom161ZbójnaGóra", direction: "Zbójna Góra")],
    "162" : [PreferredRouteModel(routeName: "TP-HAL", direction: "pl.Hallera"), PreferredRouteModel(routeName: "TP-SIE", direction: "EC Siekierki")],
    "163" : [PreferredRouteModel(routeName: "Custom163CentrumOnkologii", direction: "Centrum Onkologii"), PreferredRouteModel(routeName: "Custom163MetroWilanowska", direction: "Metro Wilanowska")],
    "164" : [PreferredRouteModel(routeName: "Custom164KępaZawadowska", direction: "Kępa Zawadowska"), PreferredRouteModel(routeName: "Custom164MetroWilanowska", direction: "Metro Wilanowska")],
    "165" : [PreferredRouteModel(routeName: "TP-WIL", direction: "Metro Wilanowska"), PreferredRouteModel(routeName: "TP-WYC", direction: "Wyczółki")],
    "166" : [PreferredRouteModel(routeName: "TP-HAL", direction: "pl.Hallera"), PreferredRouteModel(routeName: "TP-MKA", direction: "Os.Kabaty")],
    "167" : [PreferredRouteModel(routeName: "Custom167StareBemowo", direction: "Stare Bemowo"), PreferredRouteModel(routeName: "Custom167SiekierkiSanktuarium", direction: "Siekierki-Sanktuarium")],
    "168" : [PreferredRouteModel(routeName: "TX-WIT", direction: "Witolin"), PreferredRouteModel(routeName: "TX-SPA", direction: "Spartańska")],
    "169" : [PreferredRouteModel(routeName: "TP-DWK", direction: "Dw.Wschodni (Kijowska)"), PreferredRouteModel(routeName: "TP-BRP", direction: "Bródno-Podgrodzie")],
    "170" : [PreferredRouteModel(routeName: "TP-ZAW", direction: "PKP Zacisze-Wilno"), PreferredRouteModel(routeName: "TP-RST", direction: "Rondo Starzyńskiego")],
    "171" : [PreferredRouteModel(routeName: "TP-CHO", direction: "Chomiczówka"), PreferredRouteModel(routeName: "TP-TOR", direction: "Torwar")],
    "172" : [PreferredRouteModel(routeName: "TX-BER", direction: "Berestecka"), PreferredRouteModel(routeName: "TP-SAD", direction: "Sadyba")],
    "173" : [PreferredRouteModel(routeName: "TP-DWL", direction: "Dw.Wschodni (Lubelska)"), PreferredRouteModel(routeName: "TP-SMG", direction: "Stara Miłosna (Graniczna)")],
    "174" : [PreferredRouteModel(routeName: "TP-RON", direction: "Rondo ONZ"), PreferredRouteModel(routeName: "TP-BOK", direction: "Bokserska")],
    "175" : [PreferredRouteModel(routeName: "TX-LOT", direction: "Terminal Autokarowy"), PreferredRouteModel(routeName: "TX-PILL", direction: "Pl.Piłsudskiego")],
    "176" : [PreferredRouteModel(routeName: "TP-MBR", direction: "Metro Bródno"), PreferredRouteModel(routeName: "TP-CHS", direction: "Choszczówka")],
    "177" : [PreferredRouteModel(routeName: "TP-URN", direction: "Ursus-Niedźwiadek"), PreferredRouteModel(routeName: "TP-GOR", direction: "Os.Górczewska")],
    "178" : [PreferredRouteModel(routeName: "TX-RDS", direction: "Rondo Daszyńskiego"), PreferredRouteModel(routeName: "TX-SKOD9", direction: "Skorosze")],
    "179" : [PreferredRouteModel(routeName: "TP-UPN", direction: "Ursynów Płn."), PreferredRouteModel(routeName: "TP-MKA", direction: "Os.Kabaty")],
    "180" : [PreferredRouteModel(routeName: "TP-WLW", direction: "Wilanów"), PreferredRouteModel(routeName: "TP-CHO", direction: "Chomiczówka")],
    "181" : [PreferredRouteModel(routeName: "TP-PLW", direction: "Pl.Wilsona"), PreferredRouteModel(routeName: "TP-CMP", direction: "Cm.Północny-Brama Gł.")],
    "182" : [PreferredRouteModel(routeName: "TP-DWZ", direction: "Dw.Zachodni"), PreferredRouteModel(routeName: "TP-WIT", direction: "Witolin")],
    "183" : [PreferredRouteModel(routeName: "TP-WIA", direction: "Wiatraczna"), PreferredRouteModel(routeName: "TP-ZIE", direction: "Zielona")],
    "184" : [PreferredRouteModel(routeName: "TP-SZC", direction: "Szczęśliwice"), PreferredRouteModel(routeName: "TP-MML", direction: "Metro Młociny")],
    "185" : [PreferredRouteModel(routeName: "TO-USN", direction: "CH Ursynów"), PreferredRouteModel(routeName: "TO-GWI", direction: "Gwiaździsta")],
    "186" : [PreferredRouteModel(routeName: "TP-SZC", direction: "Szczęśliwice"), PreferredRouteModel(routeName: "TP-NWD", direction: "Nowodwory")],
    "187" : [PreferredRouteModel(routeName: "TO-URN", direction: "Ursus-Niedźwiadek"), PreferredRouteModel(routeName: "TO-CHE", direction: "Chełmska")],
    "188" : [PreferredRouteModel(routeName: "TX-LOT", direction: "Terminal Autokarowy"), PreferredRouteModel(routeName: "TX-GWS", direction: "PKP Gocławek")],
    "189" : [PreferredRouteModel(routeName: "TO-SAD", direction: "Sadyba"), PreferredRouteModel(routeName: "TO-GOR", direction: "Os.Górczewska")],
    "190" : [PreferredRouteModel(routeName: "TX-GOR", direction: "Os.Górczewska"), PreferredRouteModel(routeName: "TX-CHM-G", direction: "CH Marki")],
    "191" : [PreferredRouteModel(routeName: "Custom191Regulska", direction: "Regulska"), PreferredRouteModel(routeName: "Custom191BanachaSzpital", direction: "Banacha-Szpital")],
    "192" : [PreferredRouteModel(routeName: "Custom192Krasnowola", direction: "Krasnowola"), PreferredRouteModel(routeName: "Custom192OsKabaty", direction: "Os.Kabaty")],
    "193" : [PreferredRouteModel(routeName: "TP-UPN", direction: "Ursynów Płn."), PreferredRouteModel(routeName: "TP-BOK", direction: "Bokserska")],
    "194" : [PreferredRouteModel(routeName: "TX-CMW", direction: "Cm.Wolski"), PreferredRouteModel(routeName: "TP-GOL", direction: "PKP Gołąbki")],
    "196" : [PreferredRouteModel(routeName: "TX-RK-P2", direction: "Rembertów-Kolonia"), PreferredRouteModel(routeName: "TX-RK-L3", direction: "Rembertów-Kolonia")],
    "197" : [PreferredRouteModel(routeName: "Custom197Gwiaździsta", direction: "Gwiaździsta"), PreferredRouteModel(routeName: "Custom197CmWolski", direction: "Cm.Wolski")],
    "198" : [PreferredRouteModel(routeName: "TP-DWW-L", direction: "PKP Wesoła"), PreferredRouteModel(routeName: "TP-MIL-L", direction: "Stara Miłosna (Ułańska)")],
    "199" : [PreferredRouteModel(routeName: "TP-REM", direction: "Rembertów-Strzelnica"), PreferredRouteModel(routeName: "Custom199BródnoPodgrodzie", direction: "Bródno-Podgrodzie")],
    "201" : [PreferredRouteModel(routeName: "TP-JAN", direction: "Metro Księcia Janusza"), PreferredRouteModel(routeName: "TP-NBM", direction: "Nowe Bemowo")],
]
